#!/usr/bin/env node

const {spawn} = require('child_process');
const BASE_DIR = __dirname+'/..'

console.log(BASE_DIR)

function startDango(){
	let child = spawn('manage.py', ['runserver'],{
		cwd: BASE_DIR+'/backend',
	});

	console.log('django started on port 8000');

	child.stdout.on('data', function(data){
	 	console.log(data.toString());
	});

	child.stderr.on('data', function(data){
	 	console.error(data.toString());
	});

	child.on('exit', function(code){
		console.error('Django failed, killing dev server');
		console.error('Django exited with code: ' + code.toString());
		process.exit(1);
	});
};

function startWebPack(){
	let child = spawn('webpack-dev-server', ['--hot'], {
		cwd: BASE_DIR+'/frontend',
	});

	console.log('webpack started on port 8080');

	child.stdout.on('data', function(data){
	 	console.log(data.toString());
	});

	child.stderr.on('data', function(data){
	 	console.error(data.toString());
	});

	child.on('exit', function(code){
		console.error('Webpack failed, killing dev server');
		console.error('Webpack exited with code: ' + code.toString());
		process.exit(1);
	});
};

startDango();
startWebPack();
